/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service status
         * @description Check whether the API and each language index are ready. No key is
         *     needed, but requests are limited by IP address.
         *
         *     This endpoint returns `200` even when the solver is down. In that case,
         *     `status` is `"degraded"` and `languages` is empty. Watch the `status`
         *     field, not only the HTTP status. The only other response is `429`.
         */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List puzzle languages
         * @description List every supported language and its main rules. The response shows
         *     whether the language is ready and whether it needs a criss-cross grid.
         *     It also shows reading direction, `.puz` support, and the shortest answer.
         *
         *     `pt-BR` is accepted as input but is returned as `pt`. Both forms of
         *     Portuguese use the same data. `available: false` means word search and
         *     fill will not work for that language.
         *
         *     No key is needed, but requests are limited by IP address.
         */
        get: operations["listLanguages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/words": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search words by pattern
         * @description Search a language's word list. Use `_` or `?` for an unknown letter.
         *     Results are sorted by score, highest first.
         *
         *     Scores run from 0 to 100. A score of 40 or more is usually good for a
         *     clean fill. A search returns at most 100 words. You cannot use this
         *     endpoint to download the full word list.
         */
        get: operations["searchWords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/words/scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Score a batch of words
         * @description Get a score for each known word. Response keys match the words you sent.
         *     Unknown words are left out instead of getting a score of 0. This lets
         *     you tell the difference between an unknown word and a weak word.
         */
        post: operations["scoreWords"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clues/{word}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Clues for one answer
         * @description Find clues for one answer. The best clues come first. Repeated clues are
         *     removed.
         */
        get: operations["lookupClues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clues/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clues for many answers
         * @description Find clues for up to 500 answers in one request. The API returns up to
         *     five clues per answer. Answers with no clues are left out. Response keys
         *     may be uppercased or cleaned up for the language.
         */
        post: operations["lookupCluesBulk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clues/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate AI clues for an answer
         * @description Write new clues for one answer with AI. This feature needs a paid plan
         *     and the `solve` scope. The Free plan returns `403 MEMBERS_ONLY`.
         *
         *     Each clue includes a `token` that proves this API made it. This request
         *     does not save the clue. A clue may be added to the shared collection
         *     after you publish a puzzle that uses it.
         *
         *     `X-Ai-Clues-Remaining` shows how many AI clue requests are left this
         *     month. A value of `-1` means there is no limit.
         */
        post: operations["generateClues"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auto-fill a grid
         * @description Fill the empty cells while keeping all black cells and fixed letters.
         *     Most 15×15 grids take 1 to 30 seconds.
         *
         *     Choose the response with the `Accept` header:
         *
         *     * `application/json` waits for the final result.
         *     * `text/event-stream` sends live `session`, `progress`, `complete`, and
         *       `error` events.
         *
         *     `min_score` sets the word quality goal. The default is 40. The solver
         *     may use a lower score when a grid is hard to finish. Check
         *     `quality.rough` for those words. Send a rough fill to
         *     `POST /fill/improve` to try for cleaner words.
         *
         *     A fill can return `200` without solving the grid. Check whether
         *     `slotsFilled` equals `slotsTotal`. When nothing is filled, `reason`
         *     explains why. A server failure returns `502 UPSTREAM_UNAVAILABLE`.
         *
         *     Free accounts can fill grids up to 13×13. Paid plans can fill up to
         *     23×23. A fill or clean-up uses one monthly fill. This is true even when
         *     the solver finds no answer. `X-Fill-Quota-Remaining` shows the balance.
         *
         *     Chinese, Japanese, and Korean need criss-cross grids. The solver cannot
         *     fill dense grids in those languages.
         */
        post: operations["fillGrid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fill/improve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clean up a filled grid
         * @description Try to replace weak words with better ones. The black cells do not
         *     change. The solver may rebuild much of the fill, so many words can
         *     change at once.
         *
         *     Put theme cells in `locked`. Those cells will not change. Unknown words
         *     are treated as your own content and are also left alone.
         *
         *     `improved: false` means the fill was already clean or the remaining weak
         *     words cannot be changed. A clean-up uses one monthly fill.
         */
        post: operations["improveFill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fill/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a running fill
         * @description Stop a streaming `POST /fill`. Get the ID from the first `session` event.
         *     It also appears in the `X-Fill-Session-Id` header.
         *
         *     A finished or unknown ID still returns `200`. Nothing changes.
         */
        post: operations["cancelFill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/puzzles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List your puzzles
         * @description List the account's drafts and published puzzles. The newest edit comes
         *     first. This endpoint does not list other people's puzzles.
         */
        get: operations["listPuzzles"];
        put?: never;
        /**
         * Create a puzzle
         * @description Save a new puzzle to the account. Do not send `size`; the API gets it
         *     from the grid. The account plan controls the largest allowed grid.
         *
         *     A new puzzle is a draft unless you send `publish: true`. To publish, the
         *     puzzle needs a title and a clue for every finished answer. If it is not
         *     ready, the API returns `400 VALIDATION_ERROR` and saves nothing.
         *
         *     `publish: true` makes an unlisted public puzzle. It does not submit the
         *     puzzle to the showcase. Use `POST /puzzles/{id}/publish` with
         *     `submitToShowcase: true` for that. Unlisted puzzles are hidden from
         *     search engines unless you set `noIndex: false`.
         *
         *     Use `Idempotency-Key` to prevent copies when a request is sent twice.
         *     Reuse the same value for the same puzzle. A repeat returns the first
         *     puzzle with `200` and `Idempotent-Replayed: true`.
         *
         *     Creating a new puzzle uses one monthly puzzle. Repeats, edits, and
         *     publishing are free. `X-Puzzle-Quota-Remaining` shows the balance.
         */
        post: operations["createPuzzle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/puzzles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The puzzle's opaque 8-character id.
                 * @example k3n8q1zp
                 */
                id: components["parameters"]["PuzzleId"];
            };
            cookie?: never;
        };
        /**
         * Get one puzzle
         * @description Get one of your puzzles, or any published puzzle, by ID. Someone else's
         *     draft returns `404`. The API does not reveal whether that draft exists.
         */
        get: operations["getPuzzle"];
        put?: never;
        post?: never;
        /**
         * Delete a puzzle
         * @description Permanently delete a puzzle you own. This also deletes its version
         *     history. The API cannot undo this action.
         */
        delete: operations["deletePuzzle"];
        options?: never;
        head?: never;
        /**
         * Update a puzzle
         * @description Change one or more fields on a puzzle you own. Fields you leave out do
         *     not change. The API saves the old version first. Editing a published
         *     puzzle also runs the safety check again.
         *
         *     Take care with `clues`: it replaces the full clue set. It does not merge
         *     with old clues. If you send `clues`, include every Across and Down clue
         *     you want to keep.
         */
        patch: operations["updatePuzzle"];
        trace?: never;
    };
    "/puzzles/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish a puzzle
         * @description Publish a draft and create its public page and embed URL. Publishing
         *     also runs a safety check. The puzzle's clues may be added to the shared
         *     clue collection under the Terms of Use.
         *
         *     The puzzle is unlisted unless you send `submitToShowcase: true`. A
         *     person reviews every API showcase request; nothing is listed
         *     automatically, so send your best work. An unlisted puzzle is hidden
         *     from search engines unless you set `noIndex: false`.
         *
         *     An account can have up to three puzzles waiting for showcase review. A
         *     fourth returns `409 SHOWCASE_QUEUE_FULL` and changes nothing.
         *
         *     You may publish an already published puzzle again. This updates the
         *     optional fields and runs the safety check again. A puzzle already in the
         *     review queue keeps its place.
         */
        post: operations["publishPuzzle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/puzzles/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export a puzzle
         * @description Download a puzzle as JSON or as an Across Lite `.puz` file.
         *
         *     JSON matches `GET /puzzles/{id}`. The `.puz` format only supports some
         *     Latin-script languages. Check `puzExportable` in `GET /languages`.
         */
        get: operations["exportPuzzle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Puzzle language code. You may send `pt-BR`, but the API returns `pt`.
         *     Both use the same Portuguese data.
         * @default en
         * @example en
         * @enum {string}
         */
        LanguageCode: "en" | "es" | "fr" | "de" | "it" | "pt" | "pt-BR" | "pl" | "nl" | "zh" | "ja" | "ko" | "hi" | "ar" | "tr" | "he" | "id" | "cs" | "uk" | "ro" | "ru" | "sv" | "no" | "da" | "hr";
        /** @description One entry in the language registry. */
        Language: {
            code: components["schemas"]["LanguageCode"];
            /**
             * @description English name.
             * @example Croatian
             */
            name: string;
            /**
             * @description The language's own name.
             * @example Hrvatski
             */
            nativeName: string;
            /** @description `true` when word search and fill work for this language. */
            available: boolean;
            /**
             * @description `true` for Chinese, Japanese, and Korean. Build these as criss-cross
             *     grids. `POST /fill` cannot fill a dense grid for them.
             */
            crissCrossOnly: boolean;
            /**
             * @description `true` for a right-to-left language. The data still starts at column
             *     0. Mirror only the display.
             */
            rtl: boolean;
            /** @description `true` when this language can be saved as a `.puz` file. */
            puzExportable: boolean;
            /**
             * @description The shortest space that counts as an answer. Usually 3 cells, or 2
             *     for Chinese, Japanese, and Korean.
             * @example 3
             */
            minSlotLength: number;
        };
        Status: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /**
             * @description API contract version.
             * @example 1.0.0
             */
            version: string;
            /** @description Per-language index state, keyed by language code. */
            languages: {
                [key: string]: {
                    /** @description The word database file is present on the solver box. */
                    available: boolean;
                    /**
                     * @description `true` when the word list is already in memory. If `false`, the
                     *     first request may take a few extra seconds.
                     */
                    loaded: boolean;
                };
            };
        };
        /**
         * @description A square grid made of text rows, starting with the top row:
         *
         *     * `.`: an empty white cell the solver may fill
         *     * `#`: a black square
         *     * anything else: a fixed letter
         *
         *     A grid must be 3 to 23 cells wide, with the same number of rows. Some
         *     visible letters use more than one Unicode character. Count visible
         *     letters with a grapheme tool such as `Intl.Segmenter`, not JavaScript
         *     `.length`.
         *
         *     The API may uppercase or clean up letters for the language. The returned
         *     text may not exactly match the bytes you sent.
         * @example [
         *       "..#..",
         *       ".....",
         *       "..A..",
         *       ".....",
         *       "..#.."
         *     ]
         * @example [
         *       "ЛУНА.",
         *       ".#...",
         *       ".....",
         *       "...#.",
         *       "....."
         *     ]
         */
        Grid: string[];
        /**
         * @description Cells the clean-up must not change. Write each one as `"row,col"`, with
         *     counting from 0. Lock every cell in a theme answer to protect the answer.
         * @example [
         *       "0,0",
         *       "0,1",
         *       "0,2"
         *     ]
         */
        LockedCells: string[];
        /**
         * @description An RFC 9457 error object. Use `code` in your program. The `detail` text
         *     is for people and may change. Some errors include extra fields, such as
         *     `limit`, `remaining`, `maxGridSize`, or `requiredScope`.
         *
         *     Plan limit errors also include the current plan and a link or email for
         *     the next step. Show that information to the user.
         */
        Problem: {
            /**
             * Format: uri
             * @description Link to the documentation for this error code.
             * @example https://crossword.texs.org/developers/errors#RATE_LIMITED
             */
            type: string;
            /** @description Short, human-readable summary of the problem type. */
            title: string;
            /** @description The HTTP status code, repeated for clients that lose it. */
            status: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /** @description Request identifier, when one is available. */
            instance?: string;
            code: components["schemas"]["ProblemCode"];
        } & {
            [key: string]: unknown;
        };
        /**
         * @description A stable error name for programs. New codes may be added. If you do not
         *     know a code, handle it like any other error with the same HTTP status.
         *
         *     | Code | Status | Meaning |
         *     |---|---|---|
         *     | `UNAUTHORIZED` | 401 | No key, or an unknown/revoked one |
         *     | `FORBIDDEN_SCOPE` | 403 | Valid key, missing scope |
         *     | `GRID_SIZE_LOCKED` | 403 | Grid larger than the tier's `maxGridSize` |
         *     | `MEMBERS_ONLY` | 403 | Feature needs a paid membership |
         *     | `AI_QUOTA_REACHED` | 429 | Monthly AI clue allowance spent |
         *     | `FILL_QUOTA_REACHED` | 429 | Monthly fill allowance spent |
         *     | `PUZZLE_QUOTA_REACHED` | 429 | Monthly new-puzzle allowance spent |
         *     | `SHOWCASE_QUEUE_FULL` | 409 | Three puzzles already waiting for showcase review |
         *     | `RATE_LIMITED` | 429 | Per-minute limit exceeded |
         *     | `SOLVER_BUSY` | 429 | Too many solves running; retry shortly |
         *     | `LANGUAGE_UNAVAILABLE` | 400 / 503 | Unknown code, or its index could not be loaded |
         *     | `VALIDATION_ERROR` | 400 | Request body or query string is invalid |
         *     | `NOT_FOUND` | 404 | No such resource, or not yours to see |
         *     | `UPSTREAM_UNAVAILABLE` | 502 / 503 | Solver or storage unreachable |
         * @enum {string}
         */
        ProblemCode: "UNAUTHORIZED" | "FORBIDDEN_SCOPE" | "GRID_SIZE_LOCKED" | "MEMBERS_ONLY" | "AI_QUOTA_REACHED" | "FILL_QUOTA_REACHED" | "PUZZLE_QUOTA_REACHED" | "SHOWCASE_QUEUE_FULL" | "RATE_LIMITED" | "SOLVER_BUSY" | "LANGUAGE_UNAVAILABLE" | "VALIDATION_ERROR" | "NOT_FOUND" | "UPSTREAM_UNAVAILABLE";
        /** @description One entry from a word index. */
        WordMatch: {
            /**
             * @description The entry, normalized for its language.
             * @example CAT
             */
            word: string;
            /**
             * @description Word quality from 0 to 100. A score of 40 or more is usually good
             *     for a clean fill.
             * @example 80
             */
            score: number;
        };
        /** @description One clue from the corpus, or a fresh candidate from `POST /clues/generate`. */
        Clue: {
            /**
             * @description The clue itself.
             * @example Submarine sandwich
             */
            text: string;
            /**
             * @description Where the clue came from: `published`, `dictionary`, `original`, or
             *     `ai`. Only a new, unsaved `ai` clue includes a `token`.
             * @example published
             * @enum {string}
             */
            source: "published" | "dictionary" | "original" | "ai";
            /**
             * @description How many times a published clue appeared in print. Other clue types
             *     return `0`.
             * @example 118
             */
            pubCount?: number;
            /**
             * @description Proof that this API created a new AI clue. Keep it with the clue if
             *     you publish the puzzle. Saved clues leave this field out.
             */
            token?: string;
        };
        /**
         * @description A solver word with a score below 40. Words you placed, locked, or added
         *     yourself do not appear here.
         */
        RoughEntry: {
            /** @example ESNE */
            word: string;
            /** @example 25 */
            score: number;
            /** @description Zero-based row of the entry's first cell. */
            row: number;
            /** @description Zero-based column of the entry's first cell. */
            col: number;
            /** @description The clue number at that cell. */
            number: number;
            /** @enum {string} */
            direction: "across" | "down";
        };
        /**
         * @description A report on the fill. `scored` is the number of words the API checked.
         *     `rough` lists weak words, worst first. An empty list means the fill is
         *     clean. Use `POST /fill/improve` when the list is not empty.
         */
        FillQuality: {
            /** @example 76 */
            scored: number;
            rough: components["schemas"]["RoughEntry"][];
        };
        FillRequest: {
            grid: components["schemas"]["Grid"];
            /**
             * @description Word quality goal. The default is 40. The solver may use lower scores
             *     when a grid is hard to finish. Check `quality.rough` after the fill.
             * @default 40
             */
            min_score?: number;
            /**
             * @description How many seconds the solver may work. The maximum is 30 seconds.
             * @default 25
             */
            max_time?: number;
            language?: components["schemas"]["LanguageCode"];
            /**
             * @description Keep trying until `max_time` ends. Use this when a grid you know is
             *     possible returns `too_difficult`. Hard grids may use the full time.
             * @default false
             */
            try_hard_grid?: boolean;
        };
        ImproveRequest: {
            grid: components["schemas"]["Grid"];
            locked?: components["schemas"]["LockedCells"];
            language?: components["schemas"]["LanguageCode"];
            /**
             * @description Wall-clock seconds for the clean-up pass.
             * @default 25
             */
            max_time?: number;
        };
        /**
         * @description The fill result. Check whether `slotsFilled` equals `slotsTotal`. A
         *     valid request can return `200` even when the solver found no fill.
         *     Server failures return `502`.
         */
        FillResult: {
            grid: components["schemas"]["Grid"];
            /** @description Entries the solver placed. */
            slotsFilled: number;
            /**
             * @description Entries the grid has. Equal to `slotsFilled` on a complete fill; a smaller
             *     `slotsFilled` is a partial.
             */
            slotsTotal: number;
            quality: components["schemas"]["FillQuality"];
            /**
             * @description Present when no cells were filled. `too_difficult` means the solver
             *     stopped early. `no_solution` means time ran out. `cancelled` means
             *     a cancel request stopped the fill.
             * @enum {string}
             */
            reason?: "too_difficult" | "no_solution" | "cancelled";
            /** @description Also returned in `X-Fill-Session-Id`. Usable with `POST /fill/cancel`. */
            sessionId?: string;
        };
        /**
         * @description The clean-up result. `improved: false` with no `grid` means nothing
         *     changed. The fill was already clean, or locked cells forced the weak word.
         */
        ImproveResult: {
            improved: boolean;
            /** @description How many entries changed. Present when `improved` is true. */
            replaced?: number;
            grid?: components["schemas"]["Grid"];
            quality: components["schemas"]["FillQuality"];
        };
        /**
         * @description One event from a streaming fill. Events arrive in this order:
         *     `session`, zero or more `progress` events, then `complete` or `error`.
         *     The first event includes the ID needed to cancel the fill.
         */
        FillEvent: components["schemas"]["FillSessionEvent"] | components["schemas"]["FillProgressEvent"] | components["schemas"]["FillCompleteEvent"] | components["schemas"]["FillErrorEvent"];
        FillSessionEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "session";
            /** @example kKq2x9Wn0ZqQm5Yc1Lr7Hs3T */
            sessionId: string;
        };
        /**
         * @description Letters keyed by `"row,col"` (zero-based).
         * @example {
         *       "0,0": "S",
         *       "0,1": "P",
         *       "0,2": "A"
         *     }
         */
        CellLetters: {
            [key: string]: string;
        };
        /**
         * @description The solver's best grid so far. A later event may show fewer filled cells
         *     because the solver backed up. Always display the newest event.
         */
        FillProgressEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "progress";
            filled: number;
            total: number;
            fill: components["schemas"]["CellLetters"];
        };
        FillCompleteEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "complete";
            grid: components["schemas"]["Grid"];
            fill?: components["schemas"]["CellLetters"];
            slotsFilled: number;
            slotsTotal: number;
            quality: components["schemas"]["FillQuality"];
        };
        /**
         * @description The fill stopped. Use `reason` to learn why: `too_difficult`,
         *     `no_solution`, `cancelled`, or `internal`.
         */
        FillErrorEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
            /** @enum {string} */
            reason: "too_difficult" | "no_solution" | "cancelled" | "internal";
            /** @description Human-readable detail. English only; do not show it to end users verbatim. */
            message?: string;
        };
        /**
         * @description The puzzle's showcase review state. `null` means it was not submitted.
         *     A normal review moves from `pending` to `pre_approved`, then to
         *     `approved`. A blocked word moves it to `flagged` for a person to check.
         * @enum {string|null}
         */
        ShowcaseStatus: "pending" | "pre_approved" | "flagged" | "approved" | "rejected" | null;
        /**
         * @description How hard the puzzle is to solve. The rating looks at clue style and word
         *     difficulty. Drafts return `null`. A new publish may also return `null`
         *     while the rating is being made. Editing clues makes a new rating.
         * @enum {string|null}
         */
        Difficulty: "easy" | "medium" | "hard" | "expert" | null;
        /**
         * @description Clue text keyed by clue number. Across and Down use the numbers printed
         *     on the grid.
         * @example {
         *       "1": "Massage retreat",
         *       "4": "Toward"
         *     }
         */
        ClueMap: {
            [key: string]: string;
        };
        /** @description A saved puzzle. `size` comes from `grid` and cannot be changed directly. */
        Puzzle: {
            /** @example k3n8q1zp */
            id: string;
            title: string;
            /** @description The name printed on the puzzle. It does not have to match the account name. */
            author: string;
            language: components["schemas"]["LanguageCode"];
            readonly size: number;
            grid: components["schemas"]["Grid"];
            clues: {
                across: components["schemas"]["ClueMap"];
                down: components["schemas"]["ClueMap"];
            };
            /** @description Theme answers to highlight on the puzzle page. */
            themeWords: string[];
            /** @enum {string} */
            status: "draft" | "published";
            showcaseStatus: components["schemas"]["ShowcaseStatus"];
            /**
             * @description `true` when the safety check found adult themes. The public page has
             *     an age check, and the embed will not load. Add the same protection
             *     if you show the puzzle on your own site.
             */
            readonly adultThemes: boolean;
            difficulty: components["schemas"]["Difficulty"];
            /** @description Constructor's note shown on the puzzle page. */
            writeup?: string;
            /** @description Whether this puzzle is linked from the author's public page. */
            showProfile?: boolean;
            /** @description Author asked search engines to skip the puzzle page. */
            noIndex?: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /**
             * Format: uri
             * @description Public puzzle page. Present once `status` is `published`.
             */
            readonly url?: string;
            /**
             * Format: uri
             * @description Chrome-less frame for embedding. Present once `status` is `published`.
             */
            readonly embedUrl?: string;
        };
        /**
         * @description A new puzzle. Do not send `size`; it comes from the grid. The request
         *     body can be up to 1 MB.
         */
        PuzzleInput: {
            title: string;
            author?: string;
            language?: components["schemas"]["LanguageCode"];
            grid: components["schemas"]["Grid"];
            clues?: {
                across?: components["schemas"]["ClueMap"];
                down?: components["schemas"]["ClueMap"];
            };
            themeWords?: string[];
            /** @description Note from the puzzle maker. Text over 2,000 characters is cut short. */
            writeup?: string;
            showProfile?: boolean;
            noIndex?: boolean;
            /**
             * @description Create a public, unlisted puzzle. The puzzle needs a title and a clue
             *     for every finished answer. An invalid puzzle is not saved. Use
             *     `POST /puzzles/{id}/publish` to ask for showcase review.
             * @default false
             */
            publish?: boolean;
        };
        /**
         * @description Send only the fields you want to change. Other fields stay the same.
         *     The exception is `clues`: sending it replaces the full clue set.
         */
        PuzzlePatch: {
            title?: string;
            author?: string;
            language?: components["schemas"]["LanguageCode"];
            grid?: components["schemas"]["Grid"];
            clues?: {
                across?: components["schemas"]["ClueMap"];
                down?: components["schemas"]["ClueMap"];
            };
            themeWords?: string[];
            /** @description Note from the puzzle maker. Text over 2,000 characters is cut short. */
            writeup?: string;
            showProfile?: boolean;
            noIndex?: boolean;
        };
    };
    responses: {
        /** @description Missing, malformed, unknown or revoked key. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The key is valid but lacks the scope this operation needs. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No such puzzle, or it is a draft you do not own. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The request body or query string did not validate. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Per-minute rate limit exceeded for this key's tier. */
        RateLimited: {
            headers: {
                "Retry-After": components["headers"]["RetryAfter"];
                "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The solver or word-index service could not be reached, or the language index could not be loaded. */
        UpstreamUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /**
         * @description A 1 to 255 character value that is unique to this puzzle, such as a UUID
         *     or CMS post ID. Reusing it returns the first puzzle instead of making a
         *     copy. These values do not expire.
         * @example post-4821
         */
        IdempotencyKey: string;
        /**
         * @description The puzzle's opaque 8-character id.
         * @example k3n8q1zp
         */
        PuzzleId: string;
    };
    requestBodies: never;
    headers: {
        /**
         * @description Requests allowed in the current minute for this key's tier.
         * @example 60
         */
        XRateLimitLimit: number;
        /**
         * @description Requests left in the current minute.
         * @example 57
         */
        XRateLimitRemaining: number;
        /**
         * @description Seconds to wait before retrying.
         * @example 30
         */
        RetryAfter: number;
        /**
         * @description Fills (including clean-ups) left in the current calendar month; `-1` for unlimited tiers.
         * @example 183
         */
        XFillQuotaRemaining: number;
        /**
         * @description New puzzles left in the current calendar month; `-1` for unlimited tiers.
         * @example 27
         */
        XPuzzleQuotaRemaining: number;
        /** @description Present, and `true`, when the response is an earlier request's puzzle rather than a new one. */
        IdempotentReplayed: "true";
        /**
         * @description AI clue generations left in the current calendar month; `-1` for unlimited tiers.
         * @example 247
         */
        XAiCluesRemaining: number;
        /**
         * @description The solve's session id, for `POST /fill/cancel`.
         * @example kKq2x9Wn0ZqQm5Yc1Lr7Hs3T
         */
        XFillSessionId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `ok` when the solver is healthy. `degraded` when it is not. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    listLanguages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The language registry. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        languages: components["schemas"]["Language"][];
                    };
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    searchWords: {
        parameters: {
            query: {
                /**
                 * @description The slot pattern. `_` or `?` for an unknown cell.
                 * @example C_T
                 */
                pattern: string;
                /**
                 * @description Puzzle language code.
                 * @example en
                 */
                lang?: components["schemas"]["LanguageCode"];
                /**
                 * @description Drop entries scoring below this.
                 * @example 40
                 */
                min_score?: number;
                /** @description Maximum matches to return. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching words, best first. */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        words: components["schemas"]["WordMatch"][];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["UpstreamUnavailable"];
        };
    };
    scoreWords: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    words: string[];
                    language?: components["schemas"]["LanguageCode"];
                };
            };
        };
        responses: {
            /** @description Score per known word. */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Word → score. Unknown words are omitted. */
                        scores: {
                            [key: string]: number;
                        };
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["UpstreamUnavailable"];
        };
    };
    lookupClues: {
        parameters: {
            query?: {
                language?: components["schemas"]["LanguageCode"];
                limit?: number;
            };
            header?: never;
            path: {
                /**
                 * @description The answer. Normalized (uppercased, accents folded per language) server-side.
                 * @example SUB
                 */
                word: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Clues for the answer, best first. An answer with no clues returns an empty list. */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        clues: components["schemas"]["Clue"][];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["UpstreamUnavailable"];
        };
    };
    lookupCluesBulk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    words: string[];
                    language?: components["schemas"]["LanguageCode"];
                };
            };
        };
        responses: {
            /** @description Clues keyed by normalized answer. */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        clues: {
                            [key: string]: components["schemas"]["Clue"][];
                        };
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["UpstreamUnavailable"];
        };
    };
    generateClues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    word: string;
                    /** @default 5 */
                    count?: number;
                    language?: components["schemas"]["LanguageCode"];
                };
            };
        };
        responses: {
            /** @description Freshly written clue candidates. */
            200: {
                headers: {
                    "X-Ai-Clues-Remaining": components["headers"]["XAiCluesRemaining"];
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        clues: components["schemas"]["Clue"][];
                        /** @description AI clues left this month; `-1` for unlimited tiers. */
                        remaining?: number;
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            /** @description `FORBIDDEN_SCOPE` (key lacks `solve`), or `MEMBERS_ONLY` (Free tier). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `AI_QUOTA_REACHED` (monthly allowance spent) or `RATE_LIMITED`. */
            429: {
                headers: {
                    "Retry-After": components["headers"]["RetryAfter"];
                    "X-Ai-Clues-Remaining": components["headers"]["XAiCluesRemaining"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            502: components["responses"]["UpstreamUnavailable"];
            503: components["responses"]["UpstreamUnavailable"];
        };
    };
    fillGrid: {
        parameters: {
            query?: never;
            header?: {
                /** @description `application/json` (default) or `text/event-stream`. */
                Accept?: "application/json" | "text/event-stream";
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FillRequest"];
            };
        };
        responses: {
            /** @description The completed fill (JSON), or the progress stream (SSE). */
            200: {
                headers: {
                    "X-Fill-Session-Id": components["headers"]["XFillSessionId"];
                    "X-Fill-Quota-Remaining": components["headers"]["XFillQuotaRemaining"];
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FillResult"];
                    "text/event-stream": components["schemas"]["FillEvent"];
                };
            };
            /** @description `VALIDATION_ERROR` (bad grid) or `LANGUAGE_UNAVAILABLE`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /**
             * @description `FORBIDDEN_SCOPE`, or `GRID_SIZE_LOCKED` when the grid is larger than the
             *     caller's tier allows.
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description `RATE_LIMITED`, `FILL_QUOTA_REACHED` (monthly fills spent), or `SOLVER_BUSY`
             *     (too many solves already running; retry shortly).
             */
            429: {
                headers: {
                    "Retry-After": components["headers"]["RetryAfter"];
                    "X-Fill-Quota-Remaining": components["headers"]["XFillQuotaRemaining"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description `UPSTREAM_UNAVAILABLE`: the solver failed or the stream broke. A
             *     normal solve that finds nothing returns `200` with `reason` set.
             */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            503: components["responses"]["UpstreamUnavailable"];
        };
    };
    improveFill: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImproveRequest"];
            };
        };
        responses: {
            /** @description The clean-up result. */
            200: {
                headers: {
                    "X-Fill-Quota-Remaining": components["headers"]["XFillQuotaRemaining"];
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImproveResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            /** @description `FORBIDDEN_SCOPE` or `GRID_SIZE_LOCKED`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `RATE_LIMITED`, `FILL_QUOTA_REACHED`, or `SOLVER_BUSY`. */
            429: {
                headers: {
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            503: components["responses"]["UpstreamUnavailable"];
        };
    };
    cancelFill: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    session_id: string;
                };
            };
        };
        responses: {
            /** @description Cancellation recorded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        cancelled: boolean;
                        sessionId: string;
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["UpstreamUnavailable"];
        };
    };
    listPuzzles: {
        parameters: {
            query?: {
                /** @description Filter by lifecycle state. */
                status?: "draft" | "published";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Your puzzles. */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        puzzles: components["schemas"]["Puzzle"][];
                        total: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    createPuzzle: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description A 1 to 255 character value that is unique to this puzzle, such as a UUID
                 *     or CMS post ID. Reusing it returns the first puzzle instead of making a
                 *     copy. These values do not expire.
                 * @example post-4821
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PuzzleInput"];
            };
        };
        responses: {
            /**
             * @description This `Idempotency-Key` was already used. The API returns the first
             *     puzzle and does not read the new request body.
             */
            200: {
                headers: {
                    "Idempotent-Replayed": components["headers"]["IdempotentReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Puzzle"];
                };
            };
            /** @description The stored puzzle. */
            201: {
                headers: {
                    "X-Puzzle-Quota-Remaining": components["headers"]["XPuzzleQuotaRemaining"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Puzzle"];
                };
            };
            /**
             * @description `VALIDATION_ERROR`. With `publish: true` this also covers the
             *     publish-readiness check: a missing title, or an entry with no clue. Nothing
             *     is stored when it fails.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description `FORBIDDEN_SCOPE` or `GRID_SIZE_LOCKED`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The request body exceeds 1 MB. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description `RATE_LIMITED`, or `PUZZLE_QUOTA_REACHED` when no new puzzles are
             *     left this month. The error includes the plan and next step.
             */
            429: {
                headers: {
                    "Retry-After": components["headers"]["RetryAfter"];
                    "X-Puzzle-Quota-Remaining": components["headers"]["XPuzzleQuotaRemaining"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getPuzzle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The puzzle's opaque 8-character id.
                 * @example k3n8q1zp
                 */
                id: components["parameters"]["PuzzleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The puzzle. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Puzzle"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    deletePuzzle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The puzzle's opaque 8-character id.
                 * @example k3n8q1zp
                 */
                id: components["parameters"]["PuzzleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    updatePuzzle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The puzzle's opaque 8-character id.
                 * @example k3n8q1zp
                 */
                id: components["parameters"]["PuzzleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PuzzlePatch"];
            };
        };
        responses: {
            /** @description The updated puzzle. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Puzzle"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            /** @description `FORBIDDEN_SCOPE` or `GRID_SIZE_LOCKED`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    publishPuzzle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The puzzle's opaque 8-character id.
                 * @example k3n8q1zp
                 */
                id: components["parameters"]["PuzzleId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description Note shown on the puzzle page. Text over 2,000 characters is
                     *     cut short.
                     */
                    writeup?: string;
                    /** @description Link this puzzle from your public author page. */
                    showProfile?: boolean;
                    /** @description Hide the page from search engines. The share link still works. */
                    noIndex?: boolean;
                    /**
                     * @description Enter the public showcase review queue. Off by default.
                     * @default false
                     */
                    submitToShowcase?: boolean;
                };
            };
        };
        responses: {
            /** @description The published puzzle. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Puzzle"];
                };
            };
            /**
             * @description `VALIDATION_ERROR`: the puzzle needs a title and a clue for every
             *     finished answer. Unfinished answers do not need clues yet.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description `FORBIDDEN_SCOPE` or `GRID_SIZE_LOCKED`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            404: components["responses"]["NotFound"];
            /**
             * @description `SHOWCASE_QUEUE_FULL`: three puzzles are already waiting for review.
             *     Nothing was changed.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    exportPuzzle: {
        parameters: {
            query?: {
                /** @description Output format. */
                format?: "json" | "puz";
            };
            header?: never;
            path: {
                /**
                 * @description The puzzle's opaque 8-character id.
                 * @example k3n8q1zp
                 */
                id: components["parameters"]["PuzzleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The exported puzzle. */
            200: {
                headers: {
                    /**
                     * @description Set for `puz` only. The filename is a slug of the puzzle's title, e.g.
                     *     `attachment; filename="coastal-mini.puz"`.
                     */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Puzzle"];
                    "application/x-crossword": string;
                };
            };
            /**
             * @description `VALIDATION_ERROR`: `.puz` requested for a language that cannot be encoded
             *     in ISO-8859-1.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
}
